### ISSUE TITLE
Looks like 0.5.7 has broken things

### ISSUE THREAD

**Issue by primal100** [alexdelorenzo/aiopath#16]
Tested with python 3.8 and Python3.9. Works ok on aiopath 0.5.6

```python
async for path in AsyncPath('.').glob():
    print(path)
TypeError: func_to_async_func() takes 1 positional argument but 2 were given
```

```python
await f.read_text()
    async with self.open('r', encoding=encoding, errors=errors) as file:
AttributeError: __aexit__
```

**Comment by bronsen** [comment]
Can confirm.

Also this (from my CI):
```
>     async with self.open('r', encoding=encoding, errors=errors) as file:
E     AttributeError: __aenter__
```

**Comment by lopisan** [comment]
Same for me - 0.5.7 is broken, 0.5.6 works. Same error as @bronsen

**Comment by alexdelorenzo** [comment]
Thanks for submitting bug reports, @primal100, @bronsen , @lopisan. Sorry for breaking `aiopath` on you!

I've added [new tests here](https://github.com/alexdelorenzo/aiopath/tree/Python-3.9/tests) so that this doesn't happen again.

Version 0.5.11 on PyPI will fix your issues. You can install it like so:
```python3
python3 -m pip install aiopath==0.5.11
```

**Comment by bronsen** [comment]
Indeed aiopath 0.5.11 no longer raises the AttributeError during CI run.

**Comment by alexdelorenzo** [comment]
Glad to hear it, @bronsen.

I'm going to close this issue, feel free to comment again if anyone is still affected by this issue.
